commonConf:
  controls: group
  required:
    java.home: /opt/dtstack/java/bin
    hadoop.home.dir: /data/hadoop_base

pythonConf:
  controls: group
  optional:
    python2.path: /data/anaconda2/bin/python2
    python3.path: /data/anaconda3/bin/python3

jupyterConf:
  controls: group
  optional:
    jupyter.path: "'/data/anaconda3/bin/jupyter-lab'"
    c.NotebookApp.open_browser:
      controls: select
      values: ["True","False"]
    c.NotebookApp.allow_remote_access:
      controls: select
      values: ["True","False"]
    c.NotebookApp.ip: "'*'"
    c.NotebookApp.token: "''"
    c.NotebookApp.default_url: "'/lab'"
    c.NotebookApp.notebook_dir: "''"
    jupyter.project.root: /data/DTAiworks/Jupyter/


