required:
  host:
  port: 22
  username:
  path:
  maxTotal: 16
  maxIdle: 16
  minIdle: 16
  timeout: 0
  isUsePool: true
  maxWaitMillis: 3600000
  fileTimeout : 300000
  auth:
    - password: 1
    - rsaPath: 2
  password:
    dependencyKey: auth
    dependencyValue: 1
  rsaPath:
    dependencyKey: auth
    dependencyValue: 2
